# Generated by Django 4.2.5 on 2023-09-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayward_software', '0002_software'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=150, unique=True)),
                ('package_software', models.TextField(max_length=3)),
                ('affiliate_url', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
