# Generated by Django 4.2.5 on 2023-09-30 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayward_software', '0003_package_delete_software_remove_post_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
