# Generated by Django 4.2.5 on 2023-10-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayward_software', '0007_remove_package_affiliate_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='surrogate_key',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
